### PR TITLE
Fix Undo-Attendance bug

### LINKED ISSUE #109: Alpha bug: Edit and Attendance integration incompatability

### PR DESCRIPTION
**Pull request by AgentHagu**
Fixes #109

### CODE REVIEW

File: src/main/java/seedu/address/model/person/DaysAttended.java [hunk 1]
```diff
@@ -70,25 +70,31 @@ public int hashCode() {
...
+     *
+     * @return A new {@code DaysAttended} instance representing the updated days attended,
+     *         or 0 if the current days attended is 0.
      */
-    public void decrement() {
-        if (getDaysAttended() > 0) {
-            daysAttended.set(getDaysAttended() - 1);
-        }
+    public DaysAttended decremented() {
+        int newDays = Math.max(getValue() - 1, 0);
```
Comment (Arnaxx54) [inline src/main/java/seedu/address/model/person/DaysAttended.java:87]: Good check for ensuring minimum value of DaysAttended is always greater than or equal to zero.

**Review by Arnaxx54 — APPROVED** [review]
LGTM
