### PR TITLE
Fix Edit command duplicate person handling

### LINKED ISSUE #259: [PE-D][Tester E] Ui does not refresh for certain edit commands.
To replicate the issue, follow these steps:

1. Clear all the entries and enter:
`
student /name John Doe /gender male /contact 98765432 /email johnd@example.com /address 311, Clementi Ave 2, #02-25 /subject Physics /classes 7A,7B /attendance 0 /nok Bob Doe /emergency 87654321
`
This generates the first person.

2. Then, enter:

`
student /name John Doe /gender male /contact 91765432 /email johd@example.com /address 311, Clementi Ave 2, #02-25 /subject Physics /classes 7A,7B /attendance 0 /nok Bob Doe /emergency 87654321
`
This generates the second person with a same name but different contact and email.

3. Next, enter:

`edit 1 /contact 91765432`

**The first student's contact is successfully changed in the displayed UI. This implies that the edit has been successful**

### Observed Issues

1. The UI does not refresh to clear the command words, unlike most other edit commands. The command words remain in the input box.
2. For most other edit commands, upon a successful edit, the message box displays `edited Person: ...`. However, in this case, the message box does not refresh and only displays the message from the previous command.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: zzzlou/ped#4

### PR DESCRIPTION
**Pull request by AgentHagu**
Fixes #259 and it's duplicate issues

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -85,8 +86,10 @@ public CommandResult executeCommand(Model model) throws CommandException {
 
         Person personToEdit = lastShownList.get(index.getZeroBased());
         Person editedPerson = createEditedPerson(personToEdit, editPersonDescriptor);
+        Model modelWithoutPersonToEdit = new ModelManager(model.getAddressBook(), model.getUserPrefs());
+        modelWithoutPersonToEdit.deletePerson(personToEdit);
 
-        if (!personToEdit.isSamePerson(editedPerson) && model.hasPerson(editedPerson)) {
+        if (modelWithoutPersonToEdit.hasPerson(editedPerson)) {
             throw new CommandException(MESSAGE_DUPLICATE_PERSON);
```
Comment (nihalramesh12629) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:93]: good use of modelWithoutPersonToEdit

**Review by nihalramesh12629 — APPROVED** [review]
LGTM!
