### PR TITLE
PE-D: Update message constraints for name and phone

### LINKED ISSUE #220: [PE-D][Tester B] Wrong error message: Shows name error message when it should be for missing fields
When I key in the command (empty nok and emergency fields)
student /name Timothy /gender female /contact 98732391 /email tkjner@kdfjndkjfdfkjv /address hi /subject 023492 /classes 1A /attendance 0 /nok /emergency 

It shows the error message:
Names should only contain alphanumeric characters and spaces, and it should be blank

Even though the name is given ('Timothy') and it contains only alphanumeric characters and spaces.

I think the error message is for the missing nok, since after I added a valid nok, it shows another error message (for missing phone number). It may be good to change the error message to reflect the specific field that is missing to make it clearer for the users. 

Same thing for emergency contact - when emergency contact is missing, it shows the error message:
Phone numbers should only contain numbers, and it should be exactly 8 digits long. Maybe specify that it is the emergency phone number that has an error.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: kimberlytmq/ped#4

### PR DESCRIPTION
**Pull request by AgentHagu**
Fixes #220 

We are widening the scope of the error message by adding on more possibilities of what is wrong, so it's an acceptable bug fix according to feature freeze specifications.

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Name.java [hunk 1]
```diff
@@ -10,7 +10,7 @@
 public class Name {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Names should only contain alphanumeric characters and spaces, and it should not be blank";
+            "Names/Next of Kin should only contain alphanumeric characters and spaces, and it should not be blank";
```
Comment (nihalramesh12629) [inline src/main/java/seedu/address/model/person/Name.java:13]: Good Addition!

**Review by nihalramesh12629 — APPROVED** [review]
Lgtm!
