### PR TITLE
PE-D Edit emergency contact fix

### LINKED ISSUE #233: [PE-D][Tester C] Editing a `Teacher`'s emergency contact changes his phone number
<i><video controls><source src="https://raw.githubusercontent.com/limyixiang/ped/main/files/4bbbf6af-2e9a-45a6-bc04-630d97bf0335.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/limyixiang/ped/main/files/4bbbf6af-2e9a-45a6-bc04-630d97bf0335.mp4</i>

As shown in the above video, editing a `Teacher`'s emergency contact changes his phone number, which should not be the case. The `Teacher`'s contact number should only be able to be edited using the `/contact` field, not the `/emergency` field. 

Do make sure to fix this bug to ensure that the user does not accidentally change a `Teacher`'s contact number!

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: limyixiang/ped#7

### PR DESCRIPTION
**Pull request by AgentHagu**
Fixes #233 

Bug was due to accidentally using `setPhone` instead of `setEmergencyContact` in `EditCommandParser.java` line 81
image

Note: We still have a feature flaw that `edit` is allowed to input `/nok` and `/emergency` for teachers, even though teachers don't have those fields.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/EditCommandParser.java [hunk 1]
```diff
@@ -78,7 +78,8 @@ public EditCommand parse(String args) throws ParseException {
             editPersonDescriptor.setNextOfKin(ParserUtil.parseName(argMultimap.getValue(PREFIX_NEXT_OF_KIN).get()));
         }
         if (argMultimap.getValue(PREFIX_EMERGENCY_CONTACT).isPresent()) {
-            editPersonDescriptor.setPhone(ParserUtil.parsePhone(argMultimap.getValue(PREFIX_EMERGENCY_CONTACT).get()));
+            editPersonDescriptor.setEmergencyContact(
```
Comment (nihalramesh12629) [inline src/main/java/seedu/address/logic/parser/EditCommandParser.java:81]: good change!

**Review by nihalramesh12629 — APPROVED** [review]
LGTM!
