### PR TITLE
PE-D: Fix bug with editting subjects

### LINKED ISSUE #223: [PE-D][Tester A] Unable to add more subjects to a student after adding the student
When I add a student, I am able to add multiple subject fields corresponding to different subjects. However, when I edit a person, I am not allowed to edit the subject field such that the subject field has more than one subjects. i.e. I can only do `edit 9 /subject english`, and this will reset all the subjects that I have entered to just one english since edit replaces the field with new field. This disallows me add more subjects to the student in the future, since edit will always reset the subject field to only one subject. This is unreasonable especially since the app is for a school in which students are likely to take multiple subjects and even new subjects in new academic year.

Adding a student with multiple subjects:  

Editing a contact to add more subject fields: 

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: annabellekk/ped#10

### PR DESCRIPTION
**Pull request by AgentHagu**
Fixes #223 

Bug was due to accidentally checking for duplicate prefixes for `/subject`, preventing users from adding more than 1 subject during the `edit` command.

image

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/EditCommandParser.java [hunk 1]
```diff
@@ -52,7 +52,7 @@ public EditCommand parse(String args) throws ParseException {
         }
 
         argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_NAME, PREFIX_GENDER, PREFIX_PHONE, PREFIX_EMAIL,
-            PREFIX_ADDRESS, PREFIX_SUBJECT, PREFIX_CLASSES, PREFIX_NEXT_OF_KIN, PREFIX_EMERGENCY_CONTACT);
+            PREFIX_ADDRESS, PREFIX_CLASSES, PREFIX_NEXT_OF_KIN, PREFIX_EMERGENCY_CONTACT);
```
Comment (nihalramesh12629) [inline src/main/java/seedu/address/logic/parser/EditCommandParser.java:55]: did not catch this either, nice one!

**Review by nihalramesh12629 — APPROVED** [review]
lgtm!
