### PR TITLE
Resolve add Teacher/Student command success message

### LINKED ISSUE #117: Alpha bug: student command displays incorrect success message with incorrect fields
## Describe the bug

The `student` command success message currently includes an unnecessary "Tags:" label at the end and fails to display important fields such as subject, classes, and attendance.

## Expected behaviour 
The expected message format of the success message should be:
New student added: John Doe; Phone: 98765432; Email: johnd@example.com; Address: 311, Clementi Ave 2, #02-25; Subject: Physics; Classes: 7A, 7B; Attendance: 0

### LINKED ISSUE #128: Alpha bug: teacher command displays incorrect success message with incorrect fields
## Describe the bug

The `teacher` command success message currently includes an unnecessary "Tags:" label at the end and fails to display important fields such as subject, classes, and attendance.

## Expected behaviour 
The expected message format of the success message should be:
New teacher added: John Doe; Phone: 98765432; Email: johnd@example.com; Address: 311, Clementi Ave 2, #02-25; Subject: Physics; Classes: 7A, 7B

### LINKED ISSUE #137: Alpha Bug: Added Person Description with empty Tags
## Describe the bug

When a Teacher is added, with no tags, the description shows 
`New teacher added: Michael; Phone: 98765432; Email: johnd@example.com; Address: 311, Clementi Ave 2, #02-25; Tags: `

## Expected behaviour

Maybe the tags portion could be removed, since we are not using tags anymore.

### PR DESCRIPTION
**Pull request by amoschee**
Fixes #117 
Fixes #128 
Fixes #137

### CODE REVIEW

File: src/main/java/seedu/address/logic/Messages.java [hunk 1]
```diff
@@ -35,20 +38,67 @@ public static String getErrorMessageForDuplicatePrefixes(Prefix... duplicatePref
...
+                .append(student.getAddress())
+                .append("; Subject: ")
+                .append(student.getSubjects())
+                .append("; Classes: ")
+                .append(String.join(", ", student.getClasses()))
+                .append("; Days attended: ")
+                .append(student.getDaysAttended())
                 .append("; Tags: ");
-        person.getTags().forEach(builder::append);
+        student.getTags().forEach(builder::append);
```
Comment (nihalramesh12629) [inline src/main/java/seedu/address/logic/Messages.java:61]: Nicely done to separate this method for students and teachers

File: src/main/java/seedu/address/logic/Messages.java [hunk 2]
```diff
@@ -35,20 +38,67 @@ public static String getErrorMessageForDuplicatePrefixes(Prefix... duplicatePref
...
+                .append(teacher.getEmail())
+                .append("; Address: ")
+                .append(teacher.getAddress())
+                .append("; Subject: ")
+                .append(teacher.getSubjects())
+                .append("; Classes: ")
+                .append(String.join(", ", teacher.getClasses()))
+                .append("; Tags: ");
+        teacher.getTags().forEach(builder::append);
+        return builder.toString();
```
Comment (nihalramesh12629) [inline src/main/java/seedu/address/logic/Messages.java:85]: LGTM!

**Review by nihalramesh12629 — APPROVED** [review]
