### PR TITLE
Fix attendance functionality

### LINKED ISSUE #100: Fix Attendance Functionality

### PR DESCRIPTION
**Pull request by Arnaxx54**
Fixes #100

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java [hunk 1]
```diff
@@ -39,8 +40,12 @@ public CommandResult executeCommand(Model model) throws CommandException {
             throw new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
         }
         Person personToUnmark = lastShownList.get(targetIndex.getZeroBased());
-        model.unmarkAttendance(personToUnmark);
-        return new CommandResult(MESSAGE_SUCCESS);
+        if (personToUnmark instanceof Student) {
```
Comment (AgentHagu) [inline src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java:43]: Good check of object type to prevent accidentally trying to mark attendance of a Teacher
